travis:
  secure:
    BINSTAR_TOKEN: bRe505Lir1lxC4Brq4xcf6XJ0F9EksphnT5srBrsRj5UXwaq1kYiKl6z4YI5cxlQ5BR4CwHAk0vx1OLL8bBFKi6Many9PKg0wNslA1Ys7zt7jpevFEhw0ILOmcXVug2S3nsiSFIA3sIWOQoN15eG3QnxztFIrSmEVCwFwmVsBvOyuj4VSzVrwJvHGQfMal7183gsDBwJj8PmWE7o/B3pwpHQ07Ls7v2BsYrf7atpPGN5GigKm5Wo0LiWQBOQgrBsPj6PzuabF4nuP5ZhhfSTt1w6YqRlSeZdufFezWsc6nybOuRWAFzcQq6sV1CR6awijgNbEjQ0E2SqVLeC1b8X4j0iRbsV06gwEjS6EEG2070Yx8W1ScNqY+3emtIaxnUjDkodvYfOb/GcMLG8PsniXmwwapxAa594YHfVJ1RJpAmyxPDZoXRfeGHNM+dzuqiGeD90lEbUBd9KKT8QotV/ISaYROS9TZRbxjbbH2NeHLK2ft0FlkxYWiojdRdzv4OC9cRyCt4IttcyYkXMr+O94jOzyHJZxPo3kHJKSIb/tVqbk3MrTTljNqKKiQmFX858JhZMDy2FKWVo56fdmhlGQ8m7wK+UE0eHDuyOcGJhrNIByc/M7F92k+d1iVB/WpP92LShAkGGKJwWW5ceqGiv/XsgaqwZAV89ghhLxmgruHY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
